// students.js
const students = [
  { adno: 708, name: "Abdul Basith K.A" },
  { adno: 722, name: "Muhammd Shammas M.S" },
  { adno: 717, name: "Muhammed Fazal C.S" },
  { adno: 710, name: "Muhammed Athif U.A" },
  { adno: 715, name: "Muhammad Faheem K.M" },
  { adno: 724, name: "Muhammed Adnan M.S" },
  { adno: 726, name: "mohammed midlaj p" },
  { adno: 713, name: "Muhammed Sinan P.A" },
  { adno: 720, name: "Muhammed Faheem K.K" },
  { adno: 745, name: "Muhammed Hanan K.T" },
  { adno: 736, name: "Rahi Ameen K" },
  { adno: 707, name: "Jawhar Siddique" },
  { adno: 727, name: "Razeen M.K" },
  { adno: 694, name: "Sayeed A.S" },
  { adno: 730, name: "Adnan K.P" },
  { adno: 728, name: "Muhammed Labeeb K.K" },
  { adno: 709, name: "Muhammed Aman A.A" },
  { adno: 732, name: "Muhammed Nihal" },
  { adno: 743, name: "Haseeb P.H" },
  { adno: 716, name: "Muhammed Shabeeb T.S" },
  { adno: 712, name: "Alim Zayyan K.A" },
  { adno: 729, name: "Muhammed Ameen v.s" },
  { adno: 714, name: "Shanaj kadher M.N" },
  { adno: 739, name: "Muhammed Irfan R.M" },
  { adno: 738, name: "Mohammed P.M" },
  { adno: 725, name: "Muhammed Arshad S" },
  { adno: 731, name: "Muhammed Swabeeh T.S" },
  { adno: 741, name: "Muhammed Rabeeath" },
  { adno: 733, name: "Muhammed Aslam K.A" },
  { adno: 744, name: "Muhammed Asif T.K" }
];
